#!/usr/bin/env python

"""
CodebuildSrcFile

This module provides functionality for AWS CodeBuild source file management.
It handles:
- Preparing and uploading source code to S3
- Setting up build environment variables
- Creating and executing CodeBuild projects
- Managing buildspec configuration
- Processing build results

The main class, CodebuildSrcFile, extends ResourceCmdHelper to facilitate
AWS CodeBuild operations with proper resource management and error handling.
"""

# Copyright 2025 Gary Leong gary@config0.com
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from config0_publisher.cloud.aws.codebuild_srcfile_helper import CodebuildSrcFileHelper

if __name__ == "__main__":
    main = CodebuildSrcFileHelper()
    main.run()
