#!/usr/bin/env python
#

import os

from config0_publisher.loggerly import Config0Logger
from config0_publisher.serialization import b64_decode
from config0_publisher.cloud.aws.codebuild import CodebuildResourceHelper

class CodebuildShellout:

    def __init__(self):  

        self.classname = 'CodebuildShellout'

        self.logger = Config0Logger(self.classname,
                                    logcategory="cloudprovider")

        if "CODEBUILD_PARAMS_HASH" not in os.environ:
            raise Exception("CODEBUILD_PARAMS_HASH needs to be set as an env var")

        config0_buildparams = b64_decode(os.environ["CODEBUILD_PARAMS_HASH"])
        self.buildparams = config0_buildparams.get("inputargs")

        if config0_buildparams.get("env_vars"):
            self.buildparams["build_env_vars"] = config0_buildparams["env_vars"]

        if not self.buildparams:
            raise Exception("buildparams not found in CODEBUILD_PARAMS_HASH")

    def run(self):

        if not self.buildparams:
            raise Exception("buildparams need to be provided for Codebuild shellout")

        codebuild_helper = CodebuildResourceHelper(**self.buildparams)
        codebuild_helper.run()

        if codebuild_helper.results.get("status") is False:
            self.logger.error("codebuild failed:")
            exit(9)

        exit(0)

if __name__ == "__main__":

    main = CodebuildShellout()
    main.run()
